version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: cryptotracker-postgres
    environment:
      POSTGRES_DB: cryptotracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chee_w<a0quod5Aiphah
    ports:
      - "5432:5432"
    volumes:
      - dev-database-data:/var/lib/postgresql/data
    networks:
      - cryptotracker-network

  adminer:
    image: adminer:4-standalone
    container_name: cryptotracker-adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: dracula
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - cryptotracker-network

networks:
  cryptotracker-network:
    driver: bridge


volumes:
  dev-database-data:
    driver: local
