query GetTradingPairs($page: Int, $limit: Int, $isVisible: Boolean) {
  tradingPairsWithPagination(
    page: $page
    limit: $limit
    isVisible: $isVisible
  ) {
    pairs {
      id
      symbol
      baseAsset {
        symbol
        name
        logoUrl
      }
      quoteAsset {
        symbol
        name
        logoUrl
      }
      calculatedPrice {
        price
        timestamp
        metadata
      }
    }
    total
    page
    limit
  }
}
